### 1. ทดสอบสร้างข้อมูล (POST)
POST http://localhost:3000/salary
Content-Type: application/json

{
  "Amount": 25000,
  "PayDate": "2024-03-31",
  "Bonus": 1000,
  "Status": "Pending"
}

### 2. ทดสอบดึงข้อมูลทั้งหมด (GET)
GET http://localhost:3000/salary

PUT http://localhost:3000/salary
Content-Type: application/json

{
  "Status": "Paid",
  "Bonus": 2000
}

DELETE http://localhost:3000/salary